<?php
require_once ( __DIR__ . '/template.phtml');
ma_error_template_header('Error 404');
?>
	<div class="container">
	<div class="row">
	<div class="col-lg-12">

		<h2>Page Not Found</h2>
        <p>Sorry, your request URI was not found on this server.</p>

		<?php
		if($message){
			echo '<div>'.nl2br($message).'</div>';
			echo '<hr class="featurette-divider">';
		}
		?>
	</div>
	</div>
	</div>
<?php
ma_error_template_footer();
?>