<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>MyAdmin</title>

<link href="/webfrontend/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--
<link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
-->

<style>
/* Links */
a,
a:focus,
a:hover {
	color: #0063b9;
}

/* Custom default button */
.btn-default,
.btn-default:hover,
.btn-default:focus {
	color: #333;
	text-shadow: none; /* Prevent inheritance from `body` */
	background-color: #fff;
	border: 1px solid #ccc;
}

/*
 * Base structure
*/
html,
body {
	height: 100%;
	background-color: #dde0df;
}
body {
	color: #333;
	text-align: center;
	text-shadow: 0 1px 3px rgba(50,50,50,.2);
}

.site-wrapper {
	display: table;
	width: 100%;
	height: 100%; /* For at least Firefox */
	min-height: 100%;
	-webkit-box-shadow: inset 0 0 100px rgba(50,50,50,.3);
	box-shadow: inset 0 0 100px rgba(50,50,50,.3);
}
.site-wrapper-inner {
	display: table-cell;
	vertical-align: top;
}
.cover-container {
	margin-right: auto;
	margin-left: auto;
}

/* Padding for spacing */
.inner {
	padding: 30px;
}


/*
 * Header
 */
.masthead-brand {
	margin-top: 10px;
	margin-bottom: 10px;
}

.masthead-nav > li {
	display: inline-block;
}
.masthead-nav > li + li {
	margin-left: 20px;
}
.masthead-nav > li > a {
	padding-right: 0;
	padding-left: 0;
	font-size: 16px;
	font-weight: bold;
	color: #555; /* IE8 proofing */
	color: rgba(85,85,85,.75);
	border-bottom: 2px solid transparent;
}
.masthead-nav > li > a:hover,
.masthead-nav > li > a:focus {
	background-color: transparent;
	border-bottom-color: #a9a9a9;
	border-bottom-color: rgba(85,85,85,.25);
}
.masthead-nav > .active > a,
.masthead-nav > .active > a:hover,
.masthead-nav > .active > a:focus {
	color: #555;
	border-bottom-color: #555;
}

@media (min-width: 768px) {
	.masthead-brand {
		float: left;
	}
	.masthead-nav {
		float: right;
	}
}

/*
 * Cover
*/
.cover {
	padding: 0 20px;
}
.cover .btn-lg {
	padding: 10px 20px;
	font-weight: bold;
}
.cover .cover-heading {
	color: #b70002;
}

/*
 * Footer
*/
.mastfoot {
	color: #999; /* IE8 proofing */
	color: rgba(85,85,85,.5);
}
	
/*
 * Affix and center
*/
@media (min-width: 768px) {
	/* Pull out the header and footer */
	.masthead {
		position: fixed;
		top: 0;
	}
	.mastfoot {
		position: fixed;
		bottom: 0;
	}
	/* Start the vertical centering */
	.site-wrapper-inner {
		vertical-align: middle;
	}
	/* Handle the widths */
	.masthead,
	.mastfoot,
	.cover-container {
		width: 100%; /* Must be percentage or pixels for horizontal alignment */
	}
}

@media (min-width: 992px) {
	.masthead,
	.mastfoot,
	.cover-container {
		width: 700px;
}
</style>
</head>
<body>

<div class="site-wrapper">

	<div class="site-wrapper-inner">

		<div class="cover-container">

			<div class="masthead clearfix">
				<div class="inner">
					<h3 class="masthead-brand">MyAdmin</h3>
					<nav>
						<ul class="nav masthead-nav">
							<li class="active"><a href="#">Home</a></li>
							<li><a href="/myadmin">Admin</a></li>
							<li><a href="https://www.persianicon.com/myadmin/docs" target="_blank">Documentation</a></li>
						</ul>
					</nav>
				</div>
			</div>

			<div class="inner cover">
				<h1 class="cover-heading">MyAdmin</h1>
				<p class="lead">Simple web content management system.</p>
				<p class="lead">
					<a href="#" class="btn btn-lg btn-default">Learn more</a>
				</p>
			</div>

			<div class="mastfoot">
				<div class="inner">
					<p>Copyright (C) <a href="https://www.persianicon.com/myadmin" target="_blank">PersianIcon</a>, by <a href="https://twitter.com/ali_bakhtiar" target="_blank">@ali_bakhtiar</a>.</p>
				</div>
			</div>

		</div>

	</div>

</div>


<script src="/webfrontend/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/webfrontend/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>